name: next-app CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]
    paths:
      - "apps/next-app/**"
      - "packages/**"
      - "shared/**"
      - ".github/workflows/next-app-docker-ci.yml"
      - "package.json"

env:
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  PNPM_VERSION: 8.2.0
  NODE_VERSION: 18.*

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'area:next-app') || contains(github.event.pull_request.labels.*.name, 'next-app:enhancement') }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Next.js cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/apps/next-app/.next/cache
          key: ${{ runner.os }}-${{ runner.node }}-${{ hashFiles('**/pnpm-lock.yaml') }}-nextjs

      - name: ESLint
        run: pnpm lint --filter next-app...

      - name: Type checking
        run: pnpm type:check --filter next-app...

      - name: Unit tests
        run: pnpm test --filter next-app...

      - name: Playwright install
        run: pnpx playwright install --with-deps

      - name: E2E tests
        run: pnpm test:e2e --filter next-app...

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: tests/next-app/playwright-report/
          retention-days: 30  
