name: react-app Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]
    paths:
      - "apps/react-app/**"
      - "packages/**"
      - "shared/**"
      - ".github/workflows/react-app-docker-ci.yml"
      - "package.json"

env:
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  PNPM_VERSION: 8.2.0
  NODE_VERSION: 18.*
  GIT_HASH: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: ${{ contains(github.event.pull_request.labels.*.name, 'react-app:docker') || contains(github.event.pull_request.labels.*.name, 'react-app:enhancement') }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Builder
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/www/Dockerfile
          push: false
          load: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/react-app:${{ env.GIT_HASH }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            TURBO_TEAM=${{ env.TURBO_TEAM }}
            TURBO_TOKEN=${{ env.TURBO_TOKEN }}
